id: I11D1E89E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:43:30+00:00'
last_modified: '2022-06-08T01:34:21.250274+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20428
  title: གུ་བཀྲའི་ཆོས་འབྱུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '7138':
      image_group_id: I1KG5742
      title: ''
      total_pages: 848
      order: 1
      base_file: 7138.txt
    A75F:
      image_group_id: I1KG5743
      title: ''
      total_pages: 900
      order: 2
      base_file: A75F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
